# Uncomment the next line to define a global platform for your project
platform :ios, '10.2'

def the_pods
  pod 'Alamofire', '~> 4.7'
  pod 'AlamofireImage', '~> 3.3'
  pod 'SwiftyJSON', '~> 4.0.0'
  pod 'Alamofire-SwiftyJSON', '~> 3.0.0'
end

target 'nyt-pop' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for nyt-pop
  the_pods

  target 'nyt-popTests' do
    inherit! :search_paths
    # Pods for testing
    the_pods
  end

  target 'nyt-popUITests' do
    inherit! :search_paths
    # Pods for testing
    the_pods
  end

end
