# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'nyt-pop' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for nyt-pop
  pod 'Alamofire', '~> 4.7'
  pod 'AlamofireImage', '~> 3.3'

  target 'nyt-popTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'nyt-popUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
